# Generated by Django 4.0.4 on 2022-06-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_studentdetail_delete_studentdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('application_no', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentDetail',
        ),
    ]
