# Generated by Django 4.0.4 on 2022-06-21 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_student_delete_studentdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('higher_secondary_school_marks', models.PositiveIntegerField()),
                ('higher_secondary_school_name', models.CharField(max_length=200)),
                ('secondary_school_marks', models.PositiveIntegerField()),
                ('secdondary_school_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student_detail',
            fields=[
                ('application_no', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=500)),
                ('course', models.CharField(choices=[('1', 'B.A.'), ('2', 'B.Sc-(Non-Medical)'), ('3', 'B.Sc-IT'), ('4', 'B.Sc{Hons.}'), ('5', 'M.Sc-IT'), ('6', 'M.A.')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='academic_background',
            name='app_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.student_detail'),
        ),
    ]
