# Generated by Django 4.0.4 on 2022-06-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0007_alter_student_detail_application_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Academic_Background',
            new_name='AcademicBackground',
        ),
        migrations.RenameModel(
            old_name='registered_student',
            new_name='RegisteredStudent',
        ),
        migrations.RenameModel(
            old_name='Student_detail',
            new_name='StudentDetail',
        ),
    ]
