# Generated by Django 4.0.4 on 2022-06-21 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0008_rename_academic_background_academicbackground_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('higher_secondary_school_marks', models.PositiveIntegerField()),
                ('higher_secondary_school_name', models.CharField(max_length=200)),
                ('secondary_school_marks', models.PositiveIntegerField()),
                ('secdondary_school_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='AcademicBackground',
        ),
        migrations.AddField(
            model_name='academicdetail',
            name='application_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.studentsdetail'),
        ),
        migrations.AlterField(
            model_name='registeredstudent',
            name='app_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.academicdetail'),
        ),
        migrations.DeleteModel(
            name='StudentDetail',
        ),
    ]
