# Generated by Django 4.0.4 on 2022-06-21 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0009_academicdetail_studentsdetail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicBackground',
            fields=[
                ('application_no', models.AutoField(primary_key=True, serialize=False)),
                ('higher_secondary_school_marks', models.PositiveIntegerField()),
                ('higher_secondary_school_name', models.CharField(max_length=200)),
                ('secondary_school_marks', models.PositiveIntegerField()),
                ('secdondary_school_name', models.CharField(max_length=200)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.studentsdetail')),
            ],
        ),
        migrations.AlterField(
            model_name='registeredstudent',
            name='app_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.academicbackground'),
        ),
        migrations.DeleteModel(
            name='AcademicDetail',
        ),
    ]
