# Generated by Django 4.0.4 on 2022-06-21 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0010_academicbackground_alter_registeredstudent_app_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeredstudent',
            old_name='app_no',
            new_name='application_no',
        ),
    ]
