# Generated by Django 4.0.4 on 2022-06-21 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0011_rename_app_no_registeredstudent_application_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicsDetail',
            fields=[
                ('student_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('higher_secondary_school_marks', models.PositiveIntegerField()),
                ('higher_secondary_school_name', models.CharField(max_length=200)),
                ('secondary_school_marks', models.PositiveIntegerField()),
                ('secdondary_school_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AdmitStudent',
            fields=[
                ('roll_no', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.CharField(choices=[('1', 'B.A.'), ('2', 'B.Sc-(Non-Medical)'), ('3', 'B.Sc-IT'), ('4', 'B.Sc{Hons.}'), ('5', 'M.Sc-IT'), ('6', 'M.A.')], max_length=50)),
                ('section', models.CharField(max_length=10)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.academicsdetail')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('application_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='registeredstudent',
            name='application_no',
        ),
        migrations.DeleteModel(
            name='AcademicBackground',
        ),
        migrations.DeleteModel(
            name='RegisteredStudent',
        ),
        migrations.DeleteModel(
            name='StudentsDetail',
        ),
        migrations.AddField(
            model_name='academicsdetail',
            name='application_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.studentdetail'),
        ),
    ]
