# Generated by Django 4.0.4 on 2022-06-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0012_academicsdetail_admitstudent_studentdetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admitstudent',
            name='course',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='gender',
            field=models.CharField(max_length=50),
        ),
    ]
