# Generated by Django 4.0.4 on 2022-06-24 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0013_alter_admitstudent_course_alter_studentdetail_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='LoginDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=10)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.studentdetail', to_field='email')),
            ],
        ),
    ]
